### ISSUE TITLE
hspec-jenkins-0.1.1 build failure with hspec-*-2.4.1

### ISSUE THREAD

**Issue by DanBurton** [worksap-ate/hspec-jenkins#3]
Seen on stackage build server, reproduced locally:

```
Preprocessing library hspec-jenkins-0.1.1...
[1 of 1] Compiling Test.Hspec.Formatters.Jenkins ( lib/Test/Hspec/Formatters/Jenkins.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Test/Hspec/Formatters/Jenkins.o )

/Users/danburton/scratch/hspec-jenkins-0.1.1/lib/Test/Hspec/Formatters/Jenkins.hs:54:56:
    Couldn't match type ‘FailureReason’ with ‘[Char]’
    Expected type: Either GHC.Exception.SomeException String
      Actual type: Either GHC.Exception.SomeException FailureReason
    In the third argument of ‘either’, namely ‘err’
    In the first argument of ‘message’, namely
      ‘(either formatException id err)’
```

How I reproduced:

```
$ stack unpack hspec-jenkins-0.1.1
$ cd hspec-jenkins-0.1.1
$ <<add the following stack.yaml>>
$ stack build
````

```yaml
# stack.yaml
resolver: nightly-2016-02-10
packages:
- '.'
extra-deps:
- hspec-core-2.4.1
- hspec-2.4.1
- hspec-discover-2.4.1
- hspec-expectations-0.8.2
- call-stack-0.1.0
```
